In [1]:
from csv import reader
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import pickle

In [2]:
data_dir = '../data_new'
COPDGene_Freeze1_RNAseq_genes = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_genes.csv')
COPDGene_Freeze1_RNAseq_genes_logCPM_covAdjusted = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_genes_logCPM_covAdjusted.csv')
COPDGene_Freeze1_RNAseq_genes_logCPM_normalized = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_genes_logCPM_normalized.csv')

COPDGene_Freeze1_RNAseq_exonicParts = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_exonicParts.csv')
COPDGene_Freeze1_RNAseq_exonicParts_logCPM_covAdjusted = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_exonicParts_logCPM_covAdjusted.csv')
COPDGene_Freeze1_RNAseq_exonicParts_logCPM_normalized = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_exonicParts_logCPM_normalized.csv')

COPDGene_Freeze1_RNAseq_samples = os.path.join(data_dir, 'COPDGene_Freeze3_RNAseq_samples.csv')

In [3]:
data_dir2 = '../data_stranded2'
COPDGene_Freeze1_RNAseq_transcripts = os.path.join(data_dir2, 'COPDGene_Freeze1_RNAseq_transcripts.csv')
COPDGene_Freeze1_RNAseq_transcripts_logCPM_normalized = os.path.join(data_dir2, 'COPDGene_Freeze1_RNAseq_transcripts_logCPM_normalized.csv')

In [4]:
transcripts = pd.read_csv(COPDGene_Freeze1_RNAseq_transcripts)
transcripts_logCPM_normalized = pd.read_csv(COPDGene_Freeze1_RNAseq_transcripts_logCPM_normalized)

In [ ]:
genes = pd.read_csv(COPDGene_Freeze1_RNAseq_genes)
genes_logCPM_covAdjusted = pd.read_csv(COPDGene_Freeze1_RNAseq_genes_logCPM_covAdjusted)
genes_logCPM_normalized = pd.read_csv(COPDGene_Freeze1_RNAseq_genes_logCPM_normalized)
exonicParts = pd.read_csv(COPDGene_Freeze1_RNAseq_exonicParts)
exonicParts_logCPM_covAdjusted = pd.read_csv(COPDGene_Freeze1_RNAseq_exonicParts_logCPM_covAdjusted)
exonicParts_logCPM_normalized = pd.read_csv(COPDGene_Freeze1_RNAseq_exonicParts_logCPM_normalized)
samples = pd.read_csv(COPDGene_Freeze1_RNAseq_samples)

In [9]:
# 31008 transcripts
transcripts.head(5)

     transcript_id          gene_id
0  ENST00000390399  ENSG00000211752
1  ENST00000390449  ENSG00000211801
2  ENST00000390447  ENSG00000211799
3  ENST00000390440  ENSG00000211792
4  ENST00000390441  ENSG00000211793

In [7]:
transcripts_logCPM_normalized.head(5)

,transcript_id,11126H,10088U,12204G,14334D,12562G,14177N,18231N,17356C,12216N,...,19820L,21713C,21735M,21219U,18559V,15702L,12667U,16649M,20496P,21467N
0,ENST00000390399,2.740499,1.531084,1.805910,2.079990,1.508479,0.910052,2.261797,2.525709,2.648972,...,1.690370,3.412255,3.546369,2.736968,2.300125,1.994495,1.754485,2.437099,2.544870,2.743618
1,ENST00000390449,2.534525,1.687809,0.600366,1.940420,2.327158,1.316157,2.441831,2.743618,2.614848,...,2.328155,2.448267,3.753859,2.269051,2.326016,1.911569,2.097494,2.181889,2.021565,2.306514
2,ENST00000390447,2.960497,1.742615,1.277246,1.771573,2.035782,2.132141,2.727787,4.074265,2.483113,...,2.263066,3.036394,3.748175,2.566864,2.270339,1.498535,1.864793,2.189623,3.364277,3.004326
3,ENST00000390440,1.988027,1.084626,1.693784,1.873035,1.605301,2.092073,2.256557,2.528897,1.893506,...,1.890536,3.075391,3.383466,2.253096,2.033327,2.264344,1.275505,1.579666,1.988908,2.327298
4,ENST00000390441,2.503808,2.387207,1.764967,2.233802,1.199790,1.600579,3.189623,2.314909,2.312202,...,2.620984,3.791592,3.920776,2.460307,2.913499,3.871150,2.302534,2.695110,3.486639,3.112614

In [4]:
genes.head(5)
'''
rows: exonic parts/genes
columns: annotations on which genes, chromosomes, strand, start/end
position on chromosome, which transcript and exon the exonic
parts belong to; also gene length for genes
'''

           gene_id  Length chr strand
0  ENSG00000279928     570   1      +
1  ENSG00000225972     372   1      +
2  ENSG00000225630    1044   1      +
3  ENSG00000237973    1543   1      +
4  ENSG00000229344     682   1      +

In [7]:
genes_logCPM_covAdjusted.head(5)
'''
COPDGene_Freeze1_RNAseq_exonicParts/genes_logCPM_normalized.csv
 [ logCPM expression values for exonic parts/genes]
 rows: exonic parts/genes
 columns: samples (first column is exonic parts/genes id)
'''

,gene_id,11126H_161004_7001411_0434.bam,10088U_160912.bam,12204G_160420.bam,14334D_3924469546_4.bam,12562G_3924469546_4.bam,14177N_160729_7001411_0403_1.bam,18231N_160729_7001411_0403_1.bam,17356C_3924469546_4.bam,12216N_160617.bam,...,19820L_160912.bam,21713C_161101.bam,21735M_161101.bam,21219U_161101.bam,18559V_161101.bam,15702L_161101.bam,12667U_161101.bam,16649M_161101.bam,20496P_161101.bam,21467N_161101.bam
0,ENSG00000279928,1.080843,-3.002216,0.351185,0.447046,1.049093,-1.609210,-0.583507,-3.096497,-2.947006,...,-2.308020,-0.385663,1.017132,-2.426862,-0.780296,-0.983636,-0.110841,0.460826,0.538188,-0.862733
1,ENSG00000225972,-5.651055,-4.688494,-3.704477,-8.071136,-7.894073,-4.963153,-5.793207,-1.419574,-4.023829,...,-8.566477,-5.438080,-5.753392,-5.262699,-5.200187,-5.414510,-4.234793,-5.464177,-4.362856,-5.330603
2,ENSG00000225630,3.300433,2.911019,3.661646,3.095859,3.423348,3.450447,3.970386,3.199649,1.579911,...,3.756585,3.706964,3.211946,2.437652,3.252621,4.934753,3.839061,3.808889,0.035550,3.277698
3,ENSG00000237973,8.330588,9.569540,10.017245,7.356392,7.681669,13.640397,9.965204,7.917131,9.514953,...,7.883145,9.207074,9.906197,9.524931,8.746055,9.746898,9.369304,9.843573,9.595417,9.693571
4,ENSG00000229344,-2.367190,-2.204675,-2.034617,-1.929825,-4.600703,-4.788596,-2.939313,-2.191668,-3.633001,...,-5.126709,-1.718162,-4.219385,-3.815093,2.395647,-4.856277,-2.465929,-1.429593,-3.626057,-2.918560

In [8]:
genes_logCPM_normalized.head(5)
'''
COPDGene_Freeze1_RNAseq_exonicParts/genes_logCPM_covAdjusted.csv
 [ logCPM expression values for exonic parts/genes adjusted for covariates/SV ]
 rows: exonic parts/genes
 columns: samples (first column is exonic parts/genes id)
'''

,gene_id,11126H_161004_7001411_0434.bam,10088U_160912.bam,12204G_160420.bam,14334D_3924469546_4.bam,12562G_3924469546_4.bam,14177N_160729_7001411_0403_1.bam,18231N_160729_7001411_0403_1.bam,17356C_3924469546_4.bam,12216N_160617.bam,...,19820L_160912.bam,21713C_161101.bam,21735M_161101.bam,21219U_161101.bam,18559V_161101.bam,15702L_161101.bam,12667U_161101.bam,16649M_161101.bam,20496P_161101.bam,21467N_161101.bam
0,ENSG00000279928,0.423556,-3.674821,-0.835114,-1.316513,-0.436663,-1.896684,-0.116943,-3.689658,-3.660588,...,-3.689658,-0.597682,-0.198587,-3.068061,-1.696204,-1.777228,0.545597,-0.006256,0.468884,-1.168501
1,ENSG00000225972,-3.689658,-3.674821,-2.077049,-3.705144,-3.660588,-3.564519,-3.678670,2.245516,-2.396766,...,-3.689658,-3.688360,-3.595377,-3.068061,-3.647607,-3.642414,-2.680606,-3.454706,-3.306418,-3.657991
2,ENSG00000225630,1.498136,1.222240,0.914876,-0.681671,0.114608,-0.127730,0.890930,-0.430894,-2.396766,...,1.362172,0.179319,0.136541,-0.538338,0.091128,2.229726,2.077247,0.465440,-3.306418,0.310934
3,ENSG00000237973,2.120264,2.023059,2.466741,0.938585,2.160805,6.766327,1.924706,2.897815,1.611839,...,2.511082,2.061621,1.619052,1.257357,1.048455,1.825224,1.709785,2.029974,0.901343,2.051821
4,ENSG00000229344,-1.282243,-1.083476,-0.835114,-1.778282,-3.660588,-3.564519,-2.603036,-0.430894,-2.396766,...,-3.689658,-0.400282,-2.305111,-3.068061,3.573902,-3.642414,-0.275262,-0.708248,-1.773374,-1.168501

In [5]:
exonicParts.head(5)
'''
rows: exonic parts/genes
columns: annotations on which genes, chromosomes, strand, start/end
position on chromosome, which transcript and exon the exonic
parts belong to; also gene length for genes
'''

,id,gene_id,chr,strand,start,end,tx_name,exon_name
0,59061,ENSG00000225972,1,+,629062,629433,ENST00000416931,ENSE00001797039
1,59062,ENSG00000225630,1,+,629640,630683,ENST00000457540,ENSE00001780589
2,59063,ENSG00000237973,1,+,631074,632616,ENST00000414273,ENSE00001795950
3,59066,ENSG00000248527,1,+,633742,634375,ENST00000514057,ENSE00002056229
4,59078,ENSG00000237491,1,+,782051,782136,ENST00000434264|ENST00000457084|ENST00000609830,ENSE00001741526|ENSE00001642276

In [9]:
exonicParts_logCPM_covAdjusted.head(5)

,id,11126H_161004_7001411_0434.bam,10088U_160912.bam,12204G_160420.bam,14334D_3924469546_4.bam,12562G_3924469546_4.bam,14177N_160729_7001411_0403_1.bam,18231N_160729_7001411_0403_1.bam,17356C_3924469546_4.bam,12216N_160617.bam,...,19820L_160912.bam,21713C_161101.bam,21735M_161101.bam,21219U_161101.bam,18559V_161101.bam,15702L_161101.bam,12667U_161101.bam,16649M_161101.bam,20496P_161101.bam,21467N_161101.bam
0,59061,-7.467174,-6.383957,-5.176349,-9.627906,-9.517586,-6.495611,-7.483193,-2.827337,-5.787562,...,-10.308179,-7.181162,-7.145028,-6.724992,-6.784371,-6.916577,-5.771343,-6.977007,-6.001283,-6.982098
1,59062,2.700336,2.336738,3.133421,2.523428,2.970845,3.079642,3.557119,2.694642,1.043644,...,3.207543,3.218881,2.680266,2.087628,2.740656,4.344832,3.168526,3.331336,-0.290210,2.763787
2,59063,7.169094,8.474818,8.884141,6.173155,6.631171,12.255106,8.899952,6.885911,8.424797,...,6.722719,8.088721,8.789143,8.493130,7.672739,8.631258,8.300815,8.725675,8.527336,8.513617
3,59066,5.311554,5.564901,5.595545,5.243425,5.918741,4.648696,5.465479,5.156537,5.177586,...,5.306268,4.739864,5.125862,5.284909,5.311255,4.626487,5.226124,4.880150,5.313422,5.456062
4,59078,-12.365816,-12.196288,-10.682982,-11.932762,-11.884524,-11.523818,-10.485917,-10.912903,-10.598907,...,-12.969987,-11.368672,-11.282871,-13.119758,-12.924221,-13.097710,-11.055663,-12.856248,-12.485477,-12.033356

In [10]:
exonicParts_logCPM_normalized.head(5)

,id,11126H_161004_7001411_0434.bam,10088U_160912.bam,12204G_160420.bam,14334D_3924469546_4.bam,12562G_3924469546_4.bam,14177N_160729_7001411_0403_1.bam,18231N_160729_7001411_0403_1.bam,17356C_3924469546_4.bam,12216N_160617.bam,...,19820L_160912.bam,21713C_161101.bam,21735M_161101.bam,21219U_161101.bam,18559V_161101.bam,15702L_161101.bam,12667U_161101.bam,16649M_161101.bam,20496P_161101.bam,21467N_161101.bam
0,59061,-4.144316,-4.159757,-2.584184,-4.546407,-4.465404,-4.203992,-4.483577,1.561480,-3.336542,...,-4.329246,-4.429354,-3.485323,-2.905056,-3.987792,-4.055122,-2.889332,-3.961157,-3.754523,-4.283698
1,59062,0.823365,0.549911,0.184368,-1.619046,-0.664101,-0.895647,0.094226,-1.393491,-3.336542,...,0.693554,-0.371583,-0.365222,-0.899239,-0.471725,1.481127,1.132596,-0.173999,-3.754523,-0.403572
2,59063,1.381857,1.315872,1.577414,0.332873,1.682481,5.754508,1.250297,2.256029,0.903800,...,1.724116,1.515963,0.895155,0.523493,0.378043,1.101568,0.820737,1.264507,0.231474,1.234870
3,59066,2.912123,2.996848,2.020056,0.877025,2.027894,1.667414,2.272756,1.421510,1.223819,...,2.569314,1.617819,1.876018,1.793669,2.020894,1.577621,2.497988,1.392717,1.861935,2.037625
4,59078,-2.778207,-2.774981,-1.676032,-3.600976,-3.423881,-4.203992,-2.050495,-2.218371,-2.450214,...,-3.070517,-2.644097,-2.221479,-2.905056,-3.987792,-4.055122,-1.220046,-3.961157,-3.754523,-3.003890

In [6]:
samples.head(5)
'''
COPDGene_Freeze1_RNAseq_samples.csv
[ annotation for samples ]
rows: samples
columns: annotations on samples regarding current smoking status, smoking
amount, age, race, gender, COPD phenotype, blood cell compositions
(the 4 column names ending with _pct), and a categorical variable
for batch effect (first column is sample id).
'''

,Unnamed: 0,SmokCigNow,ATS_PackYears,Age_Enroll,race,gender,FEV1pp_utah,neutrophl_pct,lymphcyt_pct,monocyt_pct,eosinphl_pct,Lc.Batch
0,11126H,1,33.5,50.6,1,2,47.2,57,37,6,1,6093890587-3
1,10088U,1,31.8,54.5,1,1,111.1,63,20,13,4,6093890587-3
2,12204G,0,44.0,80.6,1,2,40.3,70,17,8,4,4537888645-8
3,14334D,1,36.7,51.8,2,2,92.7,50,38,10,0,3546587112-8
4,12562G,1,40.7,58.7,2,1,76.1,53,36,8,3,3546587112-8